# Generated by Django 4.0.6 on 2022-09-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main_erp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_yes', models.CharField(max_length=1)),
                ('inspection_no', models.CharField(max_length=1)),
                ('Preventitive_yes', models.CharField(max_length=1)),
                ('Preventitive_no', models.CharField(max_length=1)),
                ('repairs_yes', models.CharField(max_length=1)),
                ('repairs_no', models.CharField(max_length=1)),
                ('current_yes', models.CharField(max_length=1)),
                ('current_no', models.CharField(max_length=1)),
            ],
        ),
    ]
